"""empty message

Revision ID: 45e83913ae87
Revises: 3c2240c5c4c3
Create Date: 2023-07-03 19:50:48.251742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e83913ae87'
down_revision = '3c2240c5c4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    # ### end Alembic commands ###
