"""empty message

Revision ID: b1d1465f77e9
Revises: fb845c55a885
Create Date: 2023-08-03 14:32:21.809770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d1465f77e9'
down_revision = 'fb845c55a885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('hospital')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital', sa.VARCHAR(length=100), nullable=False))

    op.drop_table('hospital')
    # ### end Alembic commands ###
