"""empty message

Revision ID: fb845c55a885
Revises: 45e83913ae87
Create Date: 2023-07-31 15:10:22.816858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb845c55a885'
down_revision = '45e83913ae87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('blood_group', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('hospital', sa.String(length=100), nullable=False))
        batch_op.drop_column('city')
        batch_op.drop_column('area')
        batch_op.drop_column('date')
        batch_op.drop_column('state')
        batch_op.drop_column('time')
        batch_op.drop_column('name')
        batch_op.drop_column('post_code')
        batch_op.drop_column('email')
        batch_op.drop_column('vaccine')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('vaccine', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('post_code', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('time', sa.TIME(), nullable=False))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('area', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('hospital')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')
        batch_op.drop_column('blood_group')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')
        batch_op.drop_column('child_name')

    # ### end Alembic commands ###
